### ISSUE TITLE
which package and build tools to use?

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid-sphinx-themes#14]
Now that we're using npm and webpack in trypyramid.com instead of bower and gulp, should we switch the toolset?

**Comment by stevepiercy** [comment]
Also we might want to borrow some of the ideas from https://pypi.python.org/pypi/sphinx_rtd_theme for development, even though it uses bower and grunt. It could be useful when designing a few sample documentation pages.

**Comment by blaflamme** [comment]
Yes we will switch over webpack, it would be better to share the same pattern when possible.

**Comment by stevepiercy** [comment]
Sounds good. I'll create a new branch 'webpack' based on that from trypyramid.com for you to review.

I'll also create a bunch of sample pages stolen from Pyramid so we have some content to design around:
* Narrative and all its various markup bits and pieces, like code examples, admonitions, etc.
* TOC
* Glossary
* Index
* API
* Scripts

The examples, once rendered, could form the basis of tests, although I have no clue how that would work. I want to avoid another <tt> vs. <code> issue come up.

Finally, once we have a Sphinx theme for Pyramid-related projects, we could reuse this work for non-Pyramid projects.

Is that a plan? Did I miss anything?

**Comment by stevepiercy** [comment]
@blaflamme FYI, you can review my progress on the branch `webpack` in PR #15

**Comment by stevepiercy** [comment]
Closed by #17
